### ISSUE TITLE
const isNotTextNorReply = !post?.text && !post?.reply;

### ISSUE THREAD

**Issue by PRMSA** [k8adev/bluesky-vampetaco-bot#4]
```typescript
/**
     * Only replies to posts that contain text the and
     * belongs to a thread.
     */
 const isNotTextNorReply = !post?.text && !post?.reply;
 ```
 
 A postagem que não são respostas não possuem o campo reply então ele já é um valor falsy(undefined), dessa forma a condição é aceita apenas tendo um texto, já que está negando o que já é falso.
 
 Então só precisaria negar o .reply(deixar verdadeiro: !post?.reply) para passar na condição e ter a certeza que a postagem está em uma thread.

**Comment by k8adev** [comment]
O campo `text` pode não existir se a postagem for apenas imagem então é necessário checar se essa propriedade existe.
